name: setup-kicad-cli-action
description: GitHub Action to build and install the KiCAD CLI.
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: bash ./prepare.sh
    env:
      NEOMURA_SETUP_KICAD_CLI_ACTION_REPOSITORY: ${{ GITHUB.ACTION_REPOSITORY }}
      NEOMURA_SETUP_KICAD_CLI_ACTION_REF: ${{ GITHUB.ACTION_REF }}
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  # Disabled until the resolution of https://github.com/actions/runner/issues/646
  # - id: cache
  #   uses: actions/cache@v2
  #   with:
  #     path: ${{ GITHUB.ACTION_PATH }}/clone/submodules/kicad/code/kicad/build/release
  #     key: neomura-setup-kicad-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ runner.os }}-${{ steps.prepare.outputs.sha }}
  - run: ./build.sh
    # if: steps.cache.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - run: ./install.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
